### PR TITLE
fix #206 INSTALLDIR needs to end with version number

### LINKED ISSUE #206: Failed to install 6.3.1 at ElasticsearchBootstrapPassword action (works with 6.2.4)
I'm trying to install from a PowerShell script that executes the following:

```
msiexec /qn /log C:\Users\Administrator\elasticsearch_install_log.txt /i C:\Users\Administrator\Downlo
ads\elasticsearch-6.3.1.msi INSTALLDIR=C:\Users\Administrator\Elasticsearch CLUSTERNAME=my-cluster DATADIRECTORY=C:\Users\Administrator\Elasticsearch\
Data CONFIGDIRECTORY=C:\Users\Administrator\Elasticsearch\Config LOGSDIRECTORY=C:\Users\Administrator\Elasticsearch\Logs MASTERNODE=true DATANODE=tru
e
```

I've got the following on my install log:

```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetBootstrapPasswordTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchBootstrapPasswordAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 19:41:27: InstallFinalize. Return value 3.
```
This only happens when trying to install Elasticsearch 6.3.1. When I tried to install 6.2.4 using the same script everything is successful.

If I try and install 6.3.1 by double-clicking on the installer and using all the default values, the installation is successful as well.

I've tried to additionally pass the following parameters but I'm still getting the same error:

```
PLUGINS="" XPACKLICENSE=Basic BOOTSTRAPPASSWORD="" SKIPSETTINGPASSWORDS=True
```

Full installation log

```
=== Logging started: 7/12/2018  19:41:11 ===
Action start 19:41:11: INSTALL.
Action start 19:41:11: FindRelatedProducts.
Action ended 19:41:11: FindRelatedProducts. Return value 1.
Action start 19:41:11: Save_CONFIGDIRECTORY_CmdValue.
Action ended 19:41:11: Save_CONFIGDIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: Save_DATADIRECTORY_CmdValue.
Action ended 19:41:11: Save_DATADIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: Save_INSTALLDIR_CmdValue.
Action ended 19:41:11: Save_INSTALLDIR_CmdValue. Return value 1.
Action start 19:41:11: Save_LOGSDIRECTORY_CmdValue.
Action ended 19:41:11: Save_LOGSDIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: AppSearch.
Action ended 19:41:11: AppSearch. Return value 1.
Action start 19:41:11: Set_CONFIGDIRECTORY_CmdValue.
Action ended 19:41:11: Set_CONFIGDIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: Set_DATADIRECTORY_CmdValue.
Action ended 19:41:11: Set_DATADIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: Set_INSTALLDIR_CmdValue.
Action ended 19:41:11: Set_INSTALLDIR_CmdValue. Return value 1.
Action start 19:41:11: Set_LOGSDIRECTORY_CmdValue.
Action ended 19:41:11: Set_LOGSDIRECTORY_CmdValue. Return value 1.
Action start 19:41:11: LaunchConditions.
Action ended 19:41:11: LaunchConditions. Return value 1.
Action start 19:41:11: ValidateProductID.
Action ended 19:41:11: ValidateProductID. Return value 1.
Action start 19:41:11: CostInitialize.
Action ended 19:41:11: CostInitialize. Return value 1.
Action start 19:41:11: FileCost.
Action ended 19:41:11: FileCost. Return value 1.
Action start 19:41:11: CostFinalize.
Action ended 19:41:11: CostFinalize. Return value 1.
Action start 19:41:11: InstallValidate.
Action ended 19:41:11: InstallValidate. Return value 1.
Action start 19:41:11: InstallInitialize.
Action ended 19:41:11: InstallInitialize. Return value 1.
Action start 19:41:11: ElasticsearchExistingDirectoriesAction.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI9D50.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchExistingDirectoriesAction.ElasticsearchExistingDirectories
Action ended 19:41:13: ElasticsearchExistingDirectoriesAction. Return value 1.
Action start 19:41:13: ElasticsearchValidateArgumentsAction.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIA233.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchValidateArgumentsAction.ElasticsearchValidateArguments
Existing Version Installed: False
Current Version: 6.3.1
Existing Version: 
Session Installing: True
Session Uninstalling: False
Session Rollback: False
Session Upgrading: False
Passed Args:
PLACEWRITABLELOCATIONSINSAMEPATH=, INSTALLDIR=C:\Users\Administrator\Elasticsearch\, PreviousInstallationDirectory=, DATADIRECTORY=C:\Users\Administrator\Elasticsearch\Data, CONFIGDIRECTORY=C:\Users\Administrator\Elasticsearch\Config, LOGSDIRECTORY=C:\Users\Administrator\Elasticsearch\Logs, UNICASTNODES=, CLUSTERNAME=ncwp-iris, NODENAME=, MASTERNODE=true, DATANODE=true, INGESTNODE=true, SELECTEDMEMORY=, LOCKMEMORY=false, MINIMUMMASTERNODES=, NETWORKHOST=, HTTPPORT=9200, TRANSPORTPORT=9300, INSTALLASSERVICE=true, STARTAFTERINSTALL=true, STARTWHENWINDOWSSTARTS=true, USELOCALSYSTEM=true, USEEXISTINGUSER=, USENETWORKSERVICE=false, USER=, PASSWORD=**********, HTTPPROXYHOST=, HTTPPROXYPORT=, HTTPSPROXYHOST=, HTTPSPROXYPORT=, PLUGINSSTAGING=, PLUGINS=, ELASTICUSERPASSWORD=**********, KIBANAUSERPASSWORD=**********, LOGSTASHSYSTEMUSERPASSWORD=**********, XPACKSECURITYENABLED=, SKIPSETTINGPASSWORDS=, XPACKLICENSE=, BOOTSTRAPPASSWORD=**********, OPENDOCUMENTATIONAFTERINSTALLATION=
ViewModelState:
ElasticsearchInstallationModel
- IsValid = True
- ValidationFailures = 
- FirstInvalidStepValidationFailures = 
- MsiLogFileLocation = C:\Users\Administrator\elasticsearch_install_log.txt
- JavaInstalled = True
- JavaMisconfigured = False
- Using32BitJava = False
- BadElasticsearchYamlFile = False
NoticeModel
- IsValid = True

LocationsModel
- IsValid = True
- ConfigureAllLocations = True
- PlaceWritableLocationsInSamePath = False
- ConfigureLocations = True
- InstallDir = C:\Users\Administrator\Elasticsearch\6.3.1
- PreviousInstallationDirectory = 
- DataDirectory = C:\Users\Administrator\Elasticsearch\Data
- ConfigDirectory = C:\Users\Administrator\Elasticsearch\Config
- LogsDirectory = C:\Users\Administrator\Elasticsearch\Logs

ServiceModel
- IsValid = True
- InstallAsService = True
- StartAfterInstall = True
- StartWhenWindowsStarts = True
- UseLocalSystem = True
- UseExistingUser = False
- UseNetworkService = False
- User = 
- Password = 

ConfigurationModel
- IsValid = True
- UnicastNodes = 
- ClusterName = ncwp-iris
- NodeName = EC2AMAZ-TRV4UB2
- MasterNode = True
- DataNode = True
- IngestNode = True
- TotalPhysicalMemory = 4096
- SelectedMemory = 2048
- MinimumMasterNodes = 0
- LockMemory = False
- NetworkHost = 
- HttpPort = 9200
- TransportPort = 9300

PluginsModel
- IsValid = True
- Plugins = 
- InstalledPlugins = 

XPackModel
- IsValid = True
- IsRelevant = True
- NeedsPasswords = False
- XPackLicense = Basic
- CanAutomaticallySetupUsers = True
- SkipSettingPasswords = False
- XPackSecurityEnabled = False
- BootstrapPassword = False
- ElasticUserPassword = False
- KibanaUserPassword = False
- LogstashSystemUserPassword = False


Action ended 19:41:14: ElasticsearchValidateArgumentsAction. Return value 1.
Action start 19:41:14: ElasticsearchSetBootstrapPasswordAction.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIA735.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchSetBootstrapPasswordAction.ElasticsearchSetBootstrapPassword
Setting BOOTSTRAPPASSWORD to a randomly generated 20 character string
Action ended 19:41:15: ElasticsearchSetBootstrapPasswordAction. Return value 1.
Action start 19:41:15: ElasticsearchSetServiceParametersAction.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIABF9.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchSetServiceParametersAction.ElasticsearchSetServiceParameters
Setting ServiceAccount to Local System account
Action ended 19:41:16: ElasticsearchSetServiceParametersAction. Return value 1.
Action start 19:41:16: Set_ElasticsearchBootstrapPasswordAction_Props.
Action ended 19:41:16: Set_ElasticsearchBootstrapPasswordAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchCleanupAction_Props.
Action ended 19:41:16: Set_ElasticsearchCleanupAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchConfigurationAction_Props.
Action ended 19:41:16: Set_ElasticsearchConfigurationAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchDirectoriesAction_Props.
Action ended 19:41:16: Set_ElasticsearchDirectoriesAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchJvmOptionsAction_Props.
Action ended 19:41:16: Set_ElasticsearchJvmOptionsAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchPluginsAction_Props.
Action ended 19:41:16: Set_ElasticsearchPluginsAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchPreserveInstallAction_Props.
Action ended 19:41:16: Set_ElasticsearchPreserveInstallAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchRollbackDirectoriesAction_Props.
Action ended 19:41:16: Set_ElasticsearchRollbackDirectoriesAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchServiceStartTypeAction_Props.
Action ended 19:41:16: Set_ElasticsearchServiceStartTypeAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchSetupXPackPasswordsAction_Props.
Action ended 19:41:16: Set_ElasticsearchSetupXPackPasswordsAction_Props. Return value 1.
Action start 19:41:16: Set_ElasticsearchUninstallDirectoriesAction_Props.
Action ended 19:41:16: Set_ElasticsearchUninstallDirectoriesAction_Props. Return value 1.
Action start 19:41:16: Set_PreviousInstallationDirectory_Value.
Action ended 19:41:16: Set_PreviousInstallationDirectory_Value. Return value 1.
Action start 19:41:16: Set_NODENAME_Value.
Action ended 19:41:16: Set_NODENAME_Value. Return value 1.
Action start 19:41:16: ProcessComponents.
Action ended 19:41:17: ProcessComponents. Return value 1.
Action start 19:41:17: UnpublishFeatures.
Action ended 19:41:17: UnpublishFeatures. Return value 1.
Action start 19:41:17: StopServices.
Action ended 19:41:17: StopServices. Return value 1.
Action start 19:41:17: ElasticsearchPreserveInstallAction.
Action ended 19:41:17: ElasticsearchPreserveInstallAction. Return value 1.
Action start 19:41:17: DeleteServices.
Action ended 19:41:17: DeleteServices. Return value 1.
Action start 19:41:17: RemoveRegistryValues.
Action ended 19:41:17: RemoveRegistryValues. Return value 1.
Action start 19:41:17: RemoveEnvironmentStrings.
Action ended 19:41:17: RemoveEnvironmentStrings. Return value 1.
Action start 19:41:17: RemoveFiles.
Action ended 19:41:17: RemoveFiles. Return value 1.
Action start 19:41:17: RemoveFolders.
Action ended 19:41:17: RemoveFolders. Return value 1.
Action start 19:41:17: CreateFolders.
Action ended 19:41:17: CreateFolders. Return value 1.
Action start 19:41:17: InstallFiles.
Action ended 19:41:17: InstallFiles. Return value 1.
Action start 19:41:17: ElasticsearchRollbackDirectoriesAction.
Action ended 19:41:17: ElasticsearchRollbackDirectoriesAction. Return value 1.
Action start 19:41:17: ElasticsearchDirectoriesAction.
Action ended 19:41:17: ElasticsearchDirectoriesAction. Return value 1.
Action start 19:41:17: ElasticsearchConfigurationAction.
Action ended 19:41:17: ElasticsearchConfigurationAction. Return value 1.
Action start 19:41:17: ElasticsearchJvmOptionsAction.
Action ended 19:41:17: ElasticsearchJvmOptionsAction. Return value 1.
Action start 19:41:17: ElasticsearchPluginsAction.
Action ended 19:41:17: ElasticsearchPluginsAction. Return value 1.
Action start 19:41:17: ElasticsearchBootstrapPasswordAction.
Action ended 19:41:17: ElasticsearchBootstrapPasswordAction. Return value 1.
Action start 19:41:17: WriteRegistryValues.
Action ended 19:41:17: WriteRegistryValues. Return value 1.
Action start 19:41:17: WriteEnvironmentStrings.
Action ended 19:41:17: WriteEnvironmentStrings. Return value 1.
Action start 19:41:17: InstallServices.
Action ended 19:41:17: InstallServices. Return value 1.
Action start 19:41:17: StartServices.
Action ended 19:41:17: StartServices. Return value 1.
Action start 19:41:17: RegisterUser.
Action ended 19:41:17: RegisterUser. Return value 1.
Action start 19:41:17: RegisterProduct.
Action ended 19:41:17: RegisterProduct. Return value 1.
Action start 19:41:17: PublishFeatures.
Action ended 19:41:17: PublishFeatures. Return value 1.
Action start 19:41:17: PublishProduct.
Action ended 19:41:17: PublishProduct. Return value 1.
Action start 19:41:17: ElasticsearchCleanupAction.
Action ended 19:41:17: ElasticsearchCleanupAction. Return value 1.
Action start 19:41:17: InstallFinalize.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIB4C6.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPreserveInstallAction.ElasticsearchPreserveInstall
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIBF65.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchDirectoriesAction.ElasticsearchDirectories
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.CreateDirectoriesTask: Creating directories
[0] using existing data directory C:\Users\Administrator\Elasticsearch\Data using existing data directory C:\Users\Administrator\Elasticsearch\Data
[0] using existing logs directory C:\Users\Administrator\Elasticsearch\Logs using existing logs directory C:\Users\Administrator\Elasticsearch\Logs
[0] Created config directory C:\Users\Administrator\Elasticsearch\Config. Created config directory C:\Users\Administrator\Elasticsearch\Config.
Created config directory C:\Users\Administrator\Elasticsearch\Config.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIC4F4.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchConfigurationAction.ElasticsearchConfiguration
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.EditElasticsearchYamlTask: Configuring Elasticsearch
[0] reading elasticsearch.yml from C:\Users\Administrator\Elasticsearch\Config reading elasticsearch.yml from C:\Users\Administrator\Elasticsearch\Config
[0] updating elasticsearch.yml with values from configuration model updating elasticsearch.yml with values from configuration model
[0] updating elasticsearch.yml with values from locations model updating elasticsearch.yml with values from locations model
[0] updating elasticsearch.yml with values from locations model updating elasticsearch.yml with values from locations model
[0] updating elasticsearch.yml with values from x-pack model if needed updating elasticsearch.yml with values from x-pack model if needed
[0] elasticsearch.yml updated elasticsearch.yml updated
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSICA54.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchJvmOptionsAction.ElasticsearchJvmOptions
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.EditJvmOptionsTask: Updating Elasticsearch JVM options
[0] updated heap size to 2048m updated heap size to 2048m
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSICFB4.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPluginsAction.ElasticsearchPlugins
No plugins selected to install
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSID505.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetBootstrapPasswordTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchBootstrapPasswordAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 19:41:27: InstallFinalize. Return value 3.
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIDA84.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Rollback.ElasticsearchRollbackDirectoriesAction.ElasticsearchRollbackDirectories
Deleting bin\x-pack directory
Deleting plugins directory
Elastic.InstallerHosts.Elasticsearch.Tasks.Rollback.RollbackDirectoriesTask: Removing data, logs, and config directory, if created
[0] C:\Users\Administrator\Elasticsearch\Data already existed. skipping C:\Users\Administrator\Elasticsearch\Data already existed. skipping
Elasticsearch log file found: C:\Users\Administrator\Elasticsearch\Logs\ncwp-iris.log
  stopping ...
  stopped
  closing ...
  closed

[0] C:\Users\Administrator\Elasticsearch\Logs already existed. skipping C:\Users\Administrator\Elasticsearch\Logs already existed. skipping
[0] C:\Users\Administrator\Elasticsearch\Config removed C:\Users\Administrator\Elasticsearch\Config removed
Action ended 19:41:29: INSTALL. Return value 3.
Property(S): UpgradeCode = {DAAA2CBA-A1ED-4F29-AFBF-5478617B00F6}
Property(S): INSTALLDIR = C:\Users\Administrator\Elasticsearch\
Property(S): DATADIRECTORY = C:\Users\Administrator\Elasticsearch\Data
Property(S): CONFIGDIRECTORY = C:\Users\Administrator\Elasticsearch\Config
Property(S): LOGSDIRECTORY = C:\Users\Administrator\Elasticsearch\Logs
Property(S): NETFRAMEWORK45 = #460805
Property(S): INSTALLDIR.plugins = C:\Users\Administrator\Elasticsearch\plugins\
Property(S): INSTALLDIR.bin.xpack = C:\Users\Administrator\Elasticsearch\bin\x-pack\
Property(S): INSTALLDIR.bin = C:\Users\Administrator\Elasticsearch\bin\
Property(S): INSTALLDIR.bin.x_pack = C:\Users\Administrator\Elasticsearch\bin\x-pack\
Property(S): INSTALLDIR.config = C:\Users\Administrator\Elasticsearch\config\
Property(S): INSTALLDIR.lib = C:\Users\Administrator\Elasticsearch\lib\
Property(S): INSTALLDIR.modules.aggs_matrix_stats = C:\Users\Administrator\Elasticsearch\modules\aggs-matrix-stats\
Property(S): INSTALLDIR.modules.analysis_common = C:\Users\Administrator\Elasticsearch\modules\analysis-common\
Property(S): INSTALLDIR.modules.ingest_common = C:\Users\Administrator\Elasticsearch\modules\ingest-common\
Property(S): INSTALLDIR.modules.lang_expression = C:\Users\Administrator\Elasticsearch\modules\lang-expression\
Property(S): INSTALLDIR.modules.lang_mustache = C:\Users\Administrator\Elasticsearch\modules\lang-mustache\
Property(S): INSTALLDIR.modules.lang_painless = C:\Users\Administrator\Elasticsearch\modules\lang-painless\
Property(S): INSTALLDIR.modules.mapper_extras = C:\Users\Administrator\Elasticsearch\modules\mapper-extras\
Property(S): INSTALLDIR.modules.parent_join = C:\Users\Administrator\Elasticsearch\modules\parent-join\
Property(S): INSTALLDIR.modules.percolator = C:\Users\Administrator\Elasticsearch\modules\percolator\
Property(S): INSTALLDIR.modules.rank_eval = C:\Users\Administrator\Elasticsearch\modules\rank-eval\
Property(S): INSTALLDIR.modules.reindex = C:\Users\Administrator\Elasticsearch\modules\reindex\
Property(S): INSTALLDIR.modules.repository_url = C:\Users\Administrator\Elasticsearch\modules\repository-url\
Property(S): INSTALLDIR.modules.transport_netty4 = C:\Users\Administrator\Elasticsearch\modules\transport-netty4\
Property(S): INSTALLDIR.modules.tribe = C:\Users\Administrator\Elasticsearch\modules\tribe\
Property(S): INSTALLDIR.modules.x_pack = C:\Users\Administrator\Elasticsearch\modules\x-pack\
Property(S): INSTALLDIR.modules.x_pack.x_pack_core = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-core\
Property(S): INSTALLDIR.modules.x_pack.x_pack_deprecation = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-deprecation\
Property(S): INSTALLDIR.modules.x_pack.x_pack_graph = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-graph\
Property(S): INSTALLDIR.modules.x_pack.x_pack_logstash = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-logstash\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.darwin_x86_64.bin = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\darwin-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.darwin_x86_64.lib = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\darwin-x86_64\lib\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.linux_x86_64.bin = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\linux-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.linux_x86_64.lib = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\linux-x86_64\lib\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.windows_x86_64.bin = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\windows-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.resources = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\resources\
Property(S): INSTALLDIR.modules.x_pack.x_pack_monitoring = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-monitoring\
Property(S): INSTALLDIR.modules.x_pack.x_pack_rollup = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-rollup\
Property(S): INSTALLDIR.modules.x_pack.x_pack_security = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-security\
Property(S): INSTALLDIR.modules.x_pack.x_pack_sql = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-sql\
Property(S): INSTALLDIR.modules.x_pack.x_pack_upgrade = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-upgrade\
Property(S): INSTALLDIR.modules.x_pack.x_pack_watcher = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-watcher\
Property(S): PreviousInstallationDirectory = C:\Users\Administrator\Elasticsearch\
Property(S): NODENAME = EC2AMAZ-TRV4UB2
Property(S): Cmd_INSTALLDIR = C:\Users\Administrator\Elasticsearch
Property(S): Cmd_DATADIRECTORY = C:\Users\Administrator\Elasticsearch\Data
Property(S): Cmd_CONFIGDIRECTORY = C:\Users\Administrator\Elasticsearch\Config
Property(S): Cmd_LOGSDIRECTORY = C:\Users\Administrator\Elasticsearch\Logs
Property(S): ElasticsearchUninstallDirectoriesAction = **********
Property(S): ElasticsearchRollbackDirectoriesAction = **********
Property(S): ElasticsearchCleanupAction = **********
Property(S): ElasticsearchPreserveInstallAction = **********
Property(S): ElasticsearchDirectoriesAction = **********
Property(S): ElasticsearchConfigurationAction = **********
Property(S): ElasticsearchJvmOptionsAction = **********
Property(S): ElasticsearchPluginsAction = **********
Property(S): ElasticsearchBootstrapPasswordAction = **********
Property(S): ElasticsearchServiceStartTypeAction = **********
Property(S): ElasticsearchSetupXPackPasswordsAction = **********
Property(S): INSTALLDIR.modules = C:\Users\Administrator\Elasticsearch\modules\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.darwin_x86_64 = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\darwin-x86_64\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.linux_x86_64 = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\linux-x86_64\
Property(S): INSTALLDIR.modules.x_pack.x_pack_ml.platform.windows_x86_64 = C:\Users\Administrator\Elasticsearch\modules\x-pack\x-pack-ml\platform\windows-x86_64\
Property(S): Product = C:\Program Files\Elastic\Elasticsearch\
Property(S): Elastic = C:\Program Files\Elastic\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): TARGETDIR = C:\
Property(S): SourceDir = C:\Users\Administrator\Downloads\
Property(S): VersionNT = 603
Property(S): ALLUSERS = 1
Property(S): ElasticProduct = Elasticsearch
Property(S): CurrentVersion = 6.3.1
Property(S): MsiLogging = voicewarmup
Property(S): ARPNOREPAIR = yes
Property(S): ARPNOMODIFY = yes
Property(S): INSTALLASSERVICE = true
Property(S): STARTAFTERINSTALL = true
Property(S): STARTWHENWINDOWSSTARTS = true
Property(S): USELOCALSYSTEM = true
Property(S): USENETWORKSERVICE = false
Property(S): CLUSTERNAME = ncwp-iris
Property(S): MASTERNODE = true
Property(S): DATANODE = true
Property(S): INGESTNODE = true
Property(S): LOCKMEMORY = false
Property(S): HTTPPORT = 9200
Property(S): TRANSPORTPORT = 9300
Property(S): ARPHELPLINK = https://discuss.elastic.co/c/elasticsearch
Property(S): ARPPRODUCTICON = app_icon.ico
Property(S): ARPURLINFOABOUT = https://www.elastic.co/products/elasticsearch
Property(S): Manufacturer = Elastic
Property(S): ProductCode = {1C17C35C-B09F-4C5D-A271-0BA0F03D591F}
Property(S): ProductLanguage = 1033
Property(S): ProductName = Elasticsearch 6.3.1
Property(S): ProductVersion = 6.3.1
Property(S): SecureCustomProperties = NETFRAMEWORK45;NEWPRODUCTFOUND;UPGRADEFOUND
Property(S): MsiHiddenProperties = BOOTSTRAPPASSWORD;ElasticsearchBootstrapPasswordAction;ElasticsearchCleanupAction;ElasticsearchConfigurationAction;ElasticsearchDirectoriesAction;ElasticsearchJvmOptionsAction;ElasticsearchPluginsAction;ElasticsearchPreserveInstallAction;ElasticsearchRollbackDirectoriesAction;ElasticsearchServiceStartTypeAction;ElasticsearchSetupXPackPasswordsAction;ElasticsearchUninstallDirectoriesAction;ELASTICUSERPASSWORD;KIBANAUSERPASSWORD;LOGSTASHSYSTEMUSERPASSWORD;PASSWORD;ServicePassword
Property(S): MsiLogFileLocation = C:\Users\Administrator\elasticsearch_install_log.txt
Property(S): PackageCode = {0241D848-55BE-41C4-9CF5-994BC39E82D8}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): CURRENTDIRECTORY = C:\Users\Administrator\Documents
Property(S): CLIENTUILEVEL = 3
Property(S): CLIENTPROCESSID = 2952
Property(S): MsiSystemRebootPending = 1
Property(S): VersionDatabase = 200
Property(S): VersionMsi = 5.00
Property(S): ACTION = INSTALL
Property(S): VersionNT64 = 603
Property(S): WindowsBuild = 9600
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 3
Property(S): MsiNTSuiteDataCenter = 1
Property(S): WindowsFolder = C:\Windows\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\ADMINI~1\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\Administrator\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\Administrator\Favorites\
Property(S): NetHoodFolder = C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\Administrator\Documents\
Property(S): PrintHoodFolder = C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\Administrator\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\Administrator\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 4096
Property(S): VirtualMemory = 3678
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
Property(S): LogonUser = Administrator
Property(S): UserSID = S-1-5-21-1075604352-1384958726-2139486359-500
Property(S): UserLanguageID = 1033
Property(S): ComputerName = EC2AMAZ-TRV4UB2
Property(S): SystemLanguageID = 1033
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 23
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 19:41:29
Property(S): Date = 7/12/2018
Property(S): MsiNetAssemblySupport = 4.7.2053.0
Property(S): MsiWin32AssemblySupport = 6.3.14393.0
Property(S): RedirectedDllSupport = 2
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): USERNAME = EC2
Property(S): COMPANYNAME = Amazon.com
Property(S): DATABASE = C:\Windows\Installer\da3fcc7c.msi
Property(S): OriginalDatabase = C:\Users\Administrator\Downloads\elasticsearch-6.3.1.msi
Property(S): UILevel = 2
Property(S): ROOTDRIVE = C:\
Property(S): CostingComplete = 1
Property(S): OutOfDiskSpace = 0
Property(S): OutOfNoRbDiskSpace = 0
Property(S): PrimaryVolumeSpaceAvailable = 0
Property(S): PrimaryVolumeSpaceRequired = 0
Property(S): PrimaryVolumeSpaceRemaining = 0
Property(S): INSTALLLEVEL = 1
Property(S): ConfigDirectoryExists = False
Property(S): LogsDirectoryExists = True
Property(S): DataDirectoryExists = True
Property(S): BOOTSTRAPPASSWORD = **********
Property(S): ServiceAccount = .\LocalSystem
Property(S): SOURCEDIR = C:\Users\Administrator\Downloads\
Property(S): SourcedirProduct = {1C17C35C-B09F-4C5D-A271-0BA0F03D591F}
Property(S): ProductToBeRegistered = 1
MSI (s) (04:D8) [19:41:29:580]: Product: Elasticsearch 6.3.1 -- Installation failed.

MSI (s) (04:D8) [19:41:29:580]: Windows Installer installed the product. Product Name: Elasticsearch 6.3.1. Product Version: 6.3.1. Product Language: 1033. Manufacturer: Elastic. Installation success or error status: 1603.

=== Logging stopped: 7/12/2018  19:41:29 ===
```

### PR DESCRIPTION
**Pull request by Mpdreamz**
UI always passes it with the version number as do our integration tests
but we need to fail more clearly if INSTALLDIR is specified on the
command line using silent installation and not ending in the current
version number.

Updated README to include this requirement

### CODE REVIEW

File: src/InstallerHosts/Elastic.InstallerHosts/Elasticsearch/Tasks/Immediate/ValidateArgumentsTask.cs [hunk 1]
```diff
@@ -28,6 +29,11 @@ protected override bool ExecuteTask()
 				var validationFailures = ValidationFailures(failures);
 				throw new Exception("Cannot continue installation because of the following errors" + Environment.NewLine + validationFailures);
 			}
+
+			var installDir = this.Session.Get<string>("INSTALLDIR");
+			var version = this.InstallationModel.NoticeModel.CurrentVersion.ToString();
```
Comment (russcam) [inline src/InstallerHosts/Elastic.InstallerHosts/Elasticsearch/Tasks/Immediate/ValidateArgumentsTask.cs]: Can this be part of `LocationsModelValidator` and the rule for the `InstallDir` property?

File: src/InstallerHosts/Elastic.InstallerHosts/Elasticsearch/Tasks/Immediate/ValidateArgumentsTask.cs [hunk 2]
```diff
@@ -28,6 +29,11 @@ protected override bool ExecuteTask()
 				var validationFailures = ValidationFailures(failures);
 				throw new Exception("Cannot continue installation because of the following errors" + Environment.NewLine + validationFailures);
 			}
+
+			var installDir = this.Session.Get<string>("INSTALLDIR");
```
Comment (russcam) [inline src/InstallerHosts/Elastic.InstallerHosts/Elasticsearch/Tasks/Immediate/ValidateArgumentsTask.cs]: `nameof(LocationsModel.InstallDir).ToUpperInvariant()`?

Comment (Mpdreamz) [reply src/InstallerHosts/Elastic.InstallerHosts/Elasticsearch/Tasks/Immediate/ValidateArgumentsTask.cs]: The name of the property is not necessarily tied to the property name that gets emitted though. `INSTALLDIR` being a fixed default MSI property I think its better to leave as is.
